Polygon distance in tooltip
DatapuntAmsterdam/Leaflet.draw pull request #1
Opened 2017-01-03 15:06 UTC by boris-arkenaar

* Create polygon tooltip now also has the ability to show the length of the line in addition to the area of the polygon.
* Using the options you can specify the type of metric units to use (km, ha, m)
Instead of:

```
metric: true,
```

you can now also do:

```
metric: ['ha', 'm'],
```

* Using the options you can specify the precision to use for the calculated values to display:

```
precision: {
  km: 2,
  m: 1
}
```

For display values such as `2.99 km`, `3.00 km` and `1.5 m` and `1.0 m`.

2017-01-03 15:42 UTC, ErikNijland commented
Is er apart ticket voor de notatie van getallen? Als we namelijk precision gaan gebruiken dan moet het wel met de Nederlandse notatie (komma's en punten omdraaien).

2017-01-03 15:45 UTC, ErikNijland commented
Als we een pull request gaan maken voor Leaflet.draw dan ook graag de documentatie aanpassen: https://github.com/DatapuntAmsterdam/Leaflet.draw/blob/master/docs/leaflet-draw-latest.html.

2017-01-03 15:46 UTC, ErikNijland commented
De optie metric een Array meegeven is niet handig. In de originele Leaflet.draw wordt dit gebruikt om onderscheid te maken tussen metric en imperial.

Op deze manier kan je niet met imperial en precision werken. En dat heeft weer tot gevolg dat Leaflet.draw dit niet zal willen mergen.

2017-01-03 16:06 UTC, ErikNijland requested changes
Samenvattend: ik begrijp niet goed wat de nieuwe options moeten doen. Hoe verhouden de waardes uit bv. de metric array zich tot the keys uit het precision object? Staat 'ha' voor hectare?

Plus: ik vermoed dat nog niet alle functionaliteit uit het ticket erin zit: "Bij twee punten geeft deze bij cursor de lengte (van de lijn). Vanaf drie punten de lengte en oppervlakte."

Zou je anders twee Plunker voorbeelden kunnen maken? Een met de gewone Leaflet.draw en een met deze eigen variant. Dit is sowieso nodig als een Rob het functioneel moet testen.

2017-01-03 16:06 UTC, ErikNijland commented on spec/suites/GeometryUtilSpec.js
> +				expect(L.GeometryUtil.readableDistance(1500, true)).to.eql('1.50 km');
Waarom is het 1.50 km? Ik verwacht: 1500 meter of 1.500 meter of 1,5 km. Deze extra 0 maakt het verwarrend.

Dit gebeurd op meerdere plekken. Geldt niet alleen voor dit specifieke geval.

2017-01-03 16:06 UTC, ErikNijland commented on src/draw/handler/Draw.Polygon.js
> +			measurementString += '<br>' + L.GeometryUtil.readableArea(area, this.options.metric, this.options.precision);
Ook hier geldt dat alles ook zou moeten werken met imperial en nautical als we kans willen maken dit ooit te mergen met de bron.

2017-01-04 09:53 UTC, boris-arkenaar commented on spec/suites/GeometryUtilSpec.js
> +				expect(L.GeometryUtil.readableDistance(1500, true)).to.eql('1.50 km');
Dat is omdat de precision standaard op 2 staat voor kilometers.

2017-01-04 09:55 UTC, boris-arkenaar commented on src/draw/handler/Draw.Polygon.js
> +			measurementString += '<br>' + L.GeometryUtil.readableArea(area, this.options.metric, this.options.precision);
Dit is zoals het al was; er was alleen nog de mogelijkheid voor standaard imperial, of metric als het vlaggetje is gezet.

2017-01-04 10:13 UTC, boris-arkenaar commented
De notatie van getallen zou ook gelocaliseerd moeten worden inderdaad. Daar is nog geen ticket voor denk ik.

Documentatie wordt automatisch gegenereerd en hoeft niet met een pull request mee volgens mij. Ik moet de documentatie tags in de code nog wel aanpassen zie ik.

Een array voor de `metric` option is backwards compatible omdat een array truthy is en je definieert alleen een array als je metric wilt.

De genoemde functionaliteit zit erin.
Via de `feature/polygoon` branch van atlas zal ik een demo versie maken.

2017-01-04 11:24 UTC, boris-arkenaar commented
Zie demo: https://ci.datapunt.amsterdam.nl/atlas/builds/origin/feature/polygoon/#!?lat=52.3719&lon=4.9012&basiskaart=topografie&zoom=9&pagina=home

2017-01-04 15:12 UTC, ErikNijland commented
Je kunt nu nooit de totale oppervlakte zien. De lijn lengte wordt geupdate bij het bewegen van de cursor. De oppervlakte pas na het toevoegen van een nieuwe punt. Als je de meting voltooid (door weer op het begin te klikken) dan zie je de oppervlakte niet. Althans niet in de demo 'op het bakkie'.

Idem voor het bewerken van een meting.

2017-01-04 15:13 UTC, ErikNijland commented on build/docs-misc.leafdoc
> +| showLength | Bool | `true` | Show the length of the drawn line. **The area is only approximate and become less accurate the larger the polygon is.**
"The area is only approximate and become less accurate the larger the polygon is."

Ik denk niet dat dit functioneel acceptabel is. Er zijn ooit hele discussies geweest over de nauwkeurigheid van Leaflet.measure. Dit is dan een stap terug.

2017-01-04 15:14 UTC, ErikNijland commented on build/docs-misc.leafdoc
> +| metric | Bool | `true` | Use the metric measurement system.
Betekend dit dat de Array notatie niet (metric: ['ha', 'm']) meer via deze variabele kan?

2017-01-04 15:16 UTC, ErikNijland commented on build/docs-misc.leafdoc
>  | Option | Type | Default | Description
@namespace PolylineOptions staat er 2 keer in

2017-01-04 15:17 UTC, ErikNijland commented on src/draw/handler/Draw.Polygon.js
> +		metric: true,
Als dit de default setting is; zou ik niet doen ivm PR naar Leaflet.draw

2017-01-04 15:17 UTC, ErikNijland commented on src/draw/handler/Draw.Polyline.js
> +		metric: true, // Whether to use the metric measurement system or imperial
Idem

2017-01-04 15:19 UTC, ErikNijland commented on spec/suites/GeometryUtilSpec.js
> +				expect(L.GeometryUtil.readableDistance(1500, true)).to.eql('1.50 km');
Ja snap ik. Maar bij geld begrijp ik het bv. 1 Euro en 20 cent is 1,20 Euro. Daar hebben die laatste nullen nut.

Maar bij lengte ben ik geen 1,8800000 Meter. En een marathon is geen 42,195000000 kilometer).

2017-01-04 15:25 UTC, boris-arkenaar commented on build/docs-misc.leafdoc
> +| showLength | Bool | `true` | Show the length of the drawn line. **The area is only approximate and become less accurate the larger the polygon is.**
Dat is niet mijn tekst. Over de daadwerkelijke nauwkeurigheid weet ik niets.

2017-01-04 15:28 UTC, boris-arkenaar commented on build/docs-misc.leafdoc
> +| metric | Bool | `true` | Use the metric measurement system.
Dit is voor de Polyline, en daar heb ik die aanpassing niet voor doorgevoerd nee.

2017-01-04 15:29 UTC, boris-arkenaar commented on build/docs-misc.leafdoc
>  | Option | Type | Default | Description
Dit is Polygon, de vorige was Polyline.

2017-01-04 15:30 UTC, boris-arkenaar commented on src/draw/handler/Draw.Polygon.js
> +		metric: true,
Dit is de default, ook upstream. Ik had het eerst gewijzigd zonder daar erg in te hebben.

2017-01-04 15:33 UTC, boris-arkenaar commented
Zodra we deze plugin gaan gebruiken kunnen we zorgen dat bij het sluiten van een shape een popup wordt getoont met daarin omtrek en oppervlak. Dat kan zonder de plugin zelf te hoeven aanpassen.

2017-01-04 15:36 UTC, ErikNijland approved these changes

2017-01-04 15:36 UTC, merged